name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Generate an anaconda
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: iNicolaau
          gif_out_path: dist/github-snake.gif
          svg_out_path: dist/github-snake.svg
          color_snake: "#ffffff" # Cor da cobrinha
          color_dots: "#ff9000,#ff6000,#e83636,#f6e246,#f8c339" # Cores dos pontos
          
      - uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
